### ISSUE TITLE
Docs: add notes on branching

### ISSUE THREAD

**Issue by theetrain** [telusdigital/tds-community#13]
Come up with a branch convention to avoid conflicts. I propose

`type/#issue_number`
`type/package-name_developer-name`

Where `type` can be: `feat`, `fix`, or `chore`.

When complete, copy these notes to tds-core.

**Comment by ryanoglesby08** [comment]
Sure, though I'd say it doesn't matter too much. I don't see this as being a problem yet, or for a long time. I suggest not worrying about this yet, and if it becomes an issue then we address it. We already have commit message formatting, branch naming is pretty irrelevant to the overall process at this point.

I think more important is to keep branches short lived and delete them once the PR is merged.

**Comment by theetrain** [comment]
Not needed at this time.
